#!/bin/bash
#Info: Install or Update MasterNode Daemons, Masternode based on privkey.
#PerfilConectado.NET MasterNodes Installer
#TODO: to run you need to use ./Install.sh from MasterNodes folder.

#--------------------------------------------- COIN INFORMATION --------------------------------------------
# CONFIG ABOUT COIN
COIN_NAME=brofist
COLATERAL=1250PEW
CONFIG_FILE=brofist.conf
 
# ALWAYS START WITH ~/ AND DEFAULT COIN FOLDER
CONFIG_FOLDER=~/.brofistcore
COIN_DAEMON=brofistd
COIN_CLI=brofist-cli
COIN_TX=brofist-tx
COIN_QT=brofist-qt
MAX_CONNECTIONS=30
LOGINTIMESTAMPS=1
COIN_PORT=11113
RPC_PORT=12454
LISTEN_ONION=0
STAKING=0

# CHECK BOLEANS
USE_BIND=y
USE_ADDR=y
USE_SENTINEL=n

# SENTINEL CONFIGURATIONS
SENTINEL_REPO='https://github.com/omegacoinnetwork/sentinel.git'

# FILE WITH NODES IN MASTERNODE INSTALL FOLDER
FILE_NODES=~/MasterNodes/brofist/brofist_nodes.txt

# LINK TO DOWNLOAD DAEMON
COIN_TGZ_ZIP='https://github.com/modcrypto/brofist/releases/download/1.0.2.10/brofist_ubuntu_1.0.2.10.tar.gz'
# SET FOLDER IF UNZIP DAEMON IS ON SUBFOLDER?
COIN_SUBFOLDER=linux

# LINK TO DOWNLOAD BLOCKCHAIN
LINK_BLOCKCHAIN=https://github.com/modcrypto/brofist/releases/download/1.0.2.10/brofist.blockchain.data.zip
# SET FOLDER IF UNZIP BLOCKCHAIN IS ON SUBFOLDER?
BLOCKCHAIN_SUBFOLDER=data
 
# TO CONFIG
COIN_PATH=/usr/local/bin/
TMP_FOLDER=~/temp_masternodes
HOME_FOLDER=$(echo $HOME)
ALIAS=$(echo $HOSTNAME)
HOME_USER=$(echo $USER)

# DONT TOUCH
COIN_ZIP=$(echo $COIN_TGZ_ZIP | awk -F'/' '{print $NF}')
NODEIP=$(curl -s4 icanhazip.com)

#SET COLORS
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

#-------------------------------------------- LETS START ----------------------------------------

noflags() {
    echo "??????????????????????????????????????"
    echo "Usage: ./install.sh"
    echo "Example: ./install.sh"
    echo "??????????????????????????????????????"
    exit 1
}

message() {
	echo -e "+-------------------------------------------------------------------------------->>"
	echo -e "| $1"
	echo -e "+--------------------------------------------<<<"
}

error() {
	message "An error occured, you must fix it to continue!"
	exit 1
}

function install_dependences() {
    echo -e "${GREEN}Start install dependences!${NC}"
    echo -e "If prompted enter password of current user!"
	  echo -e "Installing required packages, it may take some time to finish.${NC}"
   	  sudo apt install zip >/dev/null 2>&1
		if [ "$?" -gt "0" ];
		  then
			echo -e "${RED}Not all required packages were installed properly. Try to install them manually by running the following commands:${NC}\n"
			  echo " sudo apt install zip"
		 exit 1
		fi
   clear
}

	function install_swap_file {
		echo -e "Checking if swap space is needed."
		PHYMEM=$(free -g|awk '/^Mem:/{print $2}')
		SWAP=$(free -g|awk '/^Swap:/{print $2}')
		if [ "$PHYMEM" -lt "2" ] && [ -n "$SWAP" ]
		  then
			echo -e "${GREEN}Server is running with less than 2G of RAM without SWAP, creating 2G swap file.${NC}"
			cd /
			sudo swapoff -a
			sudo touch /mnt/swap.img
			sudo chmod 755 /mnt/swap.img
			sudo dd if=/dev/zero of=/mnt/swap.img bs=1024 count=2097152
			sudo mkswap /mnt/swap.img
    		        sudo swapon /mnt/swap.img
			sudo echo "/mnt/swap.img none swap sw 0 0" | sudo tee -a /etc/fstab
			sudo sysctl vm.swappiness=60
			sudo free
			sleep 6s
		else
		  echo -e "${GREEN}Server running with at least 2G of RAM, no swap needed.${NC}"
		fi
		clear
	}
	
function backup_configs() {
   echo "Stop Service (work if you have installed with ./rebase)"
   sudo systemctl stop brofist.service
   sleep 5s
   brofist-cli stop
   echo "Wait $COIN_NAME daemon stop"
   sleep 10s
   check_daemon
   echo -e "Making backup of ${GREEN}$COIN_NAME ${NC} Wallet and Files..."  
   mkdir $TMP_FOLDER >/dev/null 2>&1
   mkdir $TMP_FOLDER/backup_files >/dev/null 2>&1
   cp $HOME_FOLDER/$CONFIG_FOLDER/*.conf $TMP_FOLDER/backup_files
   cp $HOME_FOLDER/$CONFIG_FOLDER/wallet.dat $TMP_FOLDER/backup_files
   cp -rf $HOME_FOLDER/$CONFIG_FOLDER/backups $TMP_FOLDER/backup_files
   cd $HOME_FOLDER/$CONFIG_FOLDER
   zip -r "$COIN_NAME_backup-$(date +"%Y-%m-%d %H-%M-%S").zip" *.conf wallet.dat
   cp $COIN_NAME_backup*.zip $HOME_FOLDER
}

function prepare_node() { #TODO: add error detection
	echo -e "Preparing to update ${GREEN}$COIN_NAME ${NC} Daemon..."
  mkdir $TMP_FOLDER >/dev/null 2>&1
  cd $TMP_FOLDER
	mkdir updatenode >/dev/null 2>&1
	cd $TMP_FOLDER/updatenode
	wget $COIN_TGZ_ZIP
  clear
  echo -e "uncompressing file"
	if [[ $COIN_TGZ_ZIP == *.gz ]]; then
	   cd $TMP_FOLDER/updatenode
     tar -xf  *.gz >/dev/null 2>&1
  fi
  if [[ $COIN_TGZ_ZIP == *.zip ]]; then
     cd $TMP_FOLDER/updatenode
	   unzip  *.zip >/dev/null 2>&1
  fi
  cd $TMP_FOLDER/updatenode
	rm *.gz >/dev/null 2>&1
	rm *.zip >/dev/null 2>&1
  RM_COINS=$(echo $COIN_PATH/$COIN_DAEMON $COIN_CLI $COIN_TX $COIN_QT)
  sudo rm -f $RM_COINS
  if [ -d "$TMP_FOLDER/updatenode/$COIN_SUBFOLDER" ]; then cd $TMP_FOLDER/updatenode/$COIN_SUBFOLDER && strip $COIN_DAEMON $COIN_CLI $COIN_TX $COIN_QT ; fi
	   if [ $? -ne 0 ]; then strip $COIN_DAEMON $COIN_CLI $COIN_TX $COIN_QT ; fi
	compile_error
	   if [ -d "$TMP_FOLDER/updatenode/$COIN_SUBFOLDER" ]; then cd $TMP_FOLDER/updatenode/$COIN_SUBFOLDER && chmod +x * && sudo cp -f * /usr/local/bin ; fi
	   if [ $? -ne 0 ]; then cd $TMP_FOLDER/updatenode && chmod +x * && sudo cp -f * /usr/local/bin ; fi
	clear
}

function update_blockchain() {
  echo -e "Wait some time, update blockchain!"
  check_daemon
  cd $HOME_FOLDER/$CONFIG_FOLDER 
  cd $CONFIG_FOLDER && sudo rm -rf blocks chainstate .lock db.log debug.log fee_estimates.dat governance.dat mncache.dat mnpayments.dat netfulfilled.dat peers.dat database >/dev/null 2>&1
  mkdir $TMP_FOLDER >/dev/null 2>&1
  mkdir $TMP_FOLDER/tmp_blockchain
  cd $TMP_FOLDER/tmp_blockchain
  wget -q $LINK_BLOCKCHAIN
 	if [[ $LINK_BLOCKCHAIN == *.gz ]]; then
	   cd $TMP_FOLDER/tmp_blockchain
     tar -xf  *.gz >/dev/null 2>&1
  fi
  if [[ $LINK_BLOCKCHAIN == *.zip ]]; then
     cd $TMP_FOLDER/tmp_blockchain
	   unzip  *.zip >/dev/null 2>&1
  fi
  mkdir $CONFIG_FOLDER >/dev/null 2>&1
  if [ -d "$TMP_FOLDER/tmp_blockchain/$BLOCKCHAIN_SUBFOLDER" ]; then cp -rvf $TMP_FOLDER/tmp_blockchain/$BLOCKCHAIN_SUBFOLDER/* $CONFIG_FOLDER >/dev/null 2>&1 ; fi
	if [ $? -ne 0 ]; then cp -rvf $TMP_FOLDER/tmp_blockchain/* $CONFIG_FOLDER >/dev/null 2>&1 ; fi
  cd ~ - >/dev/null 2>&1
  clear
}

function back_configs() {

}

function configfile_error() {
        echo -e " "
	echo -e "${RED}Error in create $CONFIG_FILE! ${NC}"
	echo -e " "
	echo -e "Try use this command = unzip -o $HOME_FOLDER/$COIN_NAME_backup*.zip $HOME_FOLDER/$CONFIG_FOLDER "
  echo -e "and restart $COIN_NAME daemon"
	sleep 10s
	exit 0
}
	
function install_service() {
  echo -e "${GREEN}Install Service ${NC}"
   	if [ ! -d "$TMP_FOLDER" ]; then mkdir $TMP_FOLDER; fi
	if [ $? -ne 0 ]; then error; fi
  cat << EOF > $TMP_FOLDER/$COIN_NAME.service
[Unit]
Description=$COIN_NAME service
After=network.target

[Service]
User=root
Group=root

Type=forking
#PIDFile=$CONFIG_FOLDER/$COIN_NAME.pid

ExecStart=$COIN_PATH$COIN_DAEMON -daemon -conf=$CONFIG_FOLDER/$CONFIG_FILE -datadir=$CONFIG_FOLDER
ExecStop=-$COIN_PATH$COIN_CLI -conf=$CONFIG_FOLDER/$CONFIG_FILE -datadir=$CONFIG_FOLDER stop

Restart=always
PrivateTmp=true
TimeoutStopSec=60s
TimeoutStartSec=10s
StartLimitInterval=120s
StartLimitBurst=5

[Install]
WantedBy=multi-user.target
EOF

  sudo cp $TMP_FOLDER/$COIN_NAME.service /etc/systemd/system/

  sudo systemctl daemon-reload
  sleep 3
  sudo systemctl start $COIN_NAME.service
  sudo systemctl enable $COIN_NAME.service >/dev/null 2>&1

  if [[ -z "$(ps axo cmd:100 | egrep $COIN_DAEMON)" ]]; then
    echo -e "${RED}$COIN_NAME is not running${NC}, please investigate. You should start by running $"
    echo -e "${GREEN}systemctl start $COIN_NAME.service"
    echo -e "systemctl status $COIN_NAME.service"
    echo -e "less /var/log/syslog${NC}"
    exit 1
  fi
  sleep 10s
  clear
}

# -------------------------------- GLOBAL CHECKS --------------------------------
function compile_error() {
if [ "$?" -gt "0" ];
 then
  echo -e "${RED}Failed to compile $COIN_NAME. Please investigate.${NC}"
  exit 1
fi
}

function check_linux_ver() {
if [[ $(lsb_release -d) != *16.04* ]]; then
  echo -e "${RED}You are not running Ubuntu 16.04. Installation is cancelled.${NC}"
  echo -e "${RED}If like to reinstall please use '$COIN_CLI stop' and restart ./rebase.sh.${NC}"
  echo -e "${RED}Remembr: It will remove all your configuration of the $COIN_NAME and create a new.${NC}"
  exit 1
fi

function check_daemon() {
if [ -n "$(pidof $COIN_DAEMON)" ] || [ -e "$COIN_DAEMOM" ] ; then
  echo -e "${RED}$COIN_NAME is already run with other command, you need to stop daemon before start update.${NC}"
  exit 1
fi
}


# ----------------------------- CONGRATULATIONS ---------------------------------
function last_commits() {
        echo -e "Commit lasts configs of $COIN_NAME Daemon!"
        sleep 2s
        echo -e "Starting $COIN_NAME Daemon"
	$COIN_DAEMON -daemon >/dev/null 2>&1
        sleep 15s
        message "Wait 120 seconds to $COIN_NAME start sync"
        sleep 120s
        clear

        message "Checking $COIN_NAME sync progress"
        GET_INFO=$(echo $COIN_CLI getinfo)
	echo -e "${GREEN} $GET_INFO ${NC}"
	
	message "Preparing masternode.conf file."
        echo -e "Obs: Only work if you have send ${GREEN}$COLATERAL${NC} to address ${GREEN}$COIN_ADDRESS ${NC}of ${GREEN}$COIN_NAME ${NC}and alrely get ${GREEN}1 confirmation!${NC}" 
	echo -e " "
	echo -e " " 
	echo -e "To create masternode.file ${GREEN}$COIN_DAEMON${NC} need ${GREEN}full sync${NC}"
	echo -e "To check it you need to open a new ssh conection and check using this command:"
	echo -e " " 
	echo -e " $COIN_CLI getinfo "
	echo -e " " 
	echo -e "Or you can press [ENTER] now and continue without complete masternode.conf if sync is not completed!" 
	echo -e "Obs.: You need to edit $CONF_FOLDER/masternode.conf and insert TXID INDEX after install complete and reboot server."
	echo -e " " 
	echo -n "Press key [ENTER] to continue..."
        read var_name
        sleep 2s
	clear

        TXOUTPUTS=$($COIN_CLI masternode outputs )
        echo -e "If you have send ammount $COLATERAL and get 1 confirmed to the $COIN_ADDRESS the OUTPUTS show now:"
	echo -e "Obs: $COIN_NAME need to be sync completed!"
        echo -e " "
	echo -e " "
	echo -e "Outputs: ${GREEN} $TXOUTPUTS ${NC}" 
	echo -e " "
	echo -e " "
	echo -e "If show none you need to complete informations in $CONFIG_FOLDER/masternode.conf manualy (TXID and INDEX)"
	sleep 10s
clear        
}

function install_sentinel() {
  SENTINELPORT=$[10001+$COIN_PORT]
  cd $HOME_FOLDER  >/dev/null 2>&1
  sudo rm -rf $HOME_FOLDER/sentinel_$COIN_NAME  #>/dev/null 2>&1
  echo -e "${GREEN}Install sentinel.${NC}"
  sudo apt-get install virtualenv >/dev/null 2>&1
  git clone $SENTINEL_REPO $HOME_FOLDER/sentinel_$COIN_NAME  >/dev/null 2>&1
  cd $HOME_FOLDER/sentinel_$COIN_NAME
  sed -i 's/#'$COIN_NAME'_conf/omegacoin_conf/g' $HOME_FOLDER/sentinel_$COIN_NAME/sentinel.conf
  sed -i "s/username/$HOME_USER/g" $HOME_FOLDER/sentinel_$COIN_NAME/sentinel.conf
  virtualenv ./venv
  ./venv/bin/pip install -r requirements.txt
  sed -i "s/19998/7777/g" $HOME_FOLDER/sentinel_$COIN_NAME/venv/bin/py.test  $HOME_FOLDER/sentinel_$COIN_NAME/test/unit/test_dash_config.py
  CRON_LINE="* * * * * cd $HOME_FOLDER/sentinel_$COIN_NAME && ./venv/bin/python bin/sentinel.py >> $HOME_FOLDER/sentinel.log >/dev/null 2>&1"
  (crontab -u $HOME_USER -l; echo "$CRON_LINE" ) | crontab -u $HOME_USER -
  (crontab -u $HOME_USER -l; echo "$CRON_LINE" ) | sudo crontab -u root -
  sudo chown -R $HOME_USER: $HOME_FOLDER/
  sudo chown -R $HOME_USER: $HOME_FOLDER/sentinel_$COIN_NAME
  ./venv/bin/py.test ./test
  echo -e "If show a ${GREEN} green massage${NC} all is ok, but if show ${RED}red message${NC} you config have a error or not all dependences installed!"
  echo -e "Getting ${RED}red${NC} message try first remove # from $HOME_FOLDER/sentinel_$COIN_NAME/sentinel.conf"
  echo -e "If dont work after remove # try reboot system"
  echo -e "Wait install continue..."
  sleep 20s
  clear
}

function success() {
TXID_INDEX=$($COIN_CLI masternode outputs)
TX_OUTPUTS=$(echo $TXID_INDEX  |  sed 's/"//g' | sed 's/{//g' |  sed 's/}//g' |  sed 's/://g')
MN_PRIVKEY=$(head -n 1 $TMP_FOLDER/$COIN_NAME.masternodeprivkey.txt)

# TO MASTERNODE CONFIG FILE
if [ ! -e "$CONFIG_FOLDER/masternode.conf" ]; then rm $CONFIG_FOLDER/masternode.conf; fi
        if [ $? -ne 0 ]; then echo -e "masternode.conf created!" ; fi
 printf "%s\n" "# Masternode config file" "# Format: alias IP:port masternodeprivkey collateral_output_txid collateral_output_index" "# Example: mn1 127.0.0.2:23403 93HaYBVUCYjEMeeH1Y4sBGLALQZE1Yc1K64xiqgX37tGBDQL8Xg 2bcd3c84c84f87eaa86e4e56834c92927a07f9e18718810b92e0d0324456a67c 0" "$ALIAS $NODEIP:$COIN_PORT $MN_PRIVKEY $TX_OUTPUTS" >  $CONFIG_FOLDER/masternode.conf
 
 # TO SHOW
 echo -e "SUCCESS! Your ${GREEN}$COIN_NAME ${NC}has started. All your configs are"
 echo -e " "
 echo -e "Obs: All informations are saved in $HOME_FOLDER/$COIN_NAME.txt !"
 echo -e " "
 message "${GREEN}CONGRATULATIONS, YOUR MASTERNODE IS INSTALLED AND CONFIGURED! ${NC}"
 echo -e "================================================================================================================================" 
 echo -e "$COIN_NAME Masternode is up and running listening on port ${RED}$COIN_PORT${NC}." 
 echo -e "Configuration file is: ${RED}$CONFIG_FOLDER/$CONFIG_FILE${NC}"
 echo -e "Start: ${RED}systemctl start $COIN_NAME.service${NC}"
 echo -e "Stop: ${RED}systemctl stop $COIN_NAME.service${NC}"
 echo -e "NODE_IP:PORT ${RED}$NODEIP:$COIN_PORT ${NC}"
 echo -e "MASTERNODE PRIVATEKEY is: ${RED} $MN_PRIVKEY ${NC}"
 echo -e "MASTERNODE file: $CONFIG_FOLDER/masternode.conf"
 echo -e "MASTERNODE configuration, copy this line bellow and paste in your windows wallet masternode file:"
 echo -e "$ALIAS $NODEIP:$COIN_PORT $MN_PRIVKEY $TX_OUTPUTS"
 echo -e "Please check ${RED}$COIN_NAME${NC} is running with the following command: ${GREEN}systemctl status $COIN_NAME.service${NC}" 
 echo -e "================================================================================================================================" 
 echo -e " "
 echo -e "================================================================================================================================" 
 echo -e "A copy of MASTERNODE file ${GREEN}$CONFIG_FOLDER/masternode.conf${NC} and"
 echo -e "a copy of CONFIG file ${GREEN}$CONFIG_FOLDER/$CONFIG_FILE ${NC}"
 echo -e "are saved in ${GREEN}$HOME_FOLDER/$COIN_NAME.txt${NC}"
 echo -e "================================================================================================================================" 

# TO COINFILE TXT
        if [ -e "$HOME_FOLDER/$COIN_NAME.txt" ]; then rm $HOME_FOLDER/$COIN_NAME.txt; fi
        if [ $? -ne 0 ]; then clear; fi
 echo -e "================================================================================================================================" >> ~/$COIN_NAME.txt
 echo -e "$COIN_NAME Masternode is up and running listening on port $COIN_PORT." >> ~/$COIN_NAME.txt
 echo -e "Configuration file is: $CONFIG_FOLDER/$CONFIG_FILE" >> ~/$COIN_NAME.txt
 echo -e "Start: systemctl start $COIN_NAME.service" >> ~/$COIN_NAME.txt
 echo -e "Stop: systemctl stop $COIN_NAME.service" >> ~/$COIN_NAME.txt
 echo -e "NODE_IP:PORT $NODEIP:$COIN_PORT" >> ~/$COIN_NAME.txt
 echo -e "MASTERNODE PRIVATEKEY is: $MN_PRIVKEY" >> ~/$COIN_NAME.txt
 echo -e "MASTERNODE file: $CONFIG_FOLDER/masternode.conf " >> ~/$COIN_NAME.txt
 echo -e "MASTERNODE configuration bellow:" >> ~/$COIN_NAME.txt
 echo -e "$ALIAS $NODEIP:$COIN_PORT $MN_PRIVKEY $TX_OUTPUTS" >> ~/$COIN_NAME.txt
 echo -e "Please check $COIN_NAME$ is running with the following command: systemctl status $COIN_NAME.service" >> ~/$COIN_NAME.txt
 echo -e "================================================================================================================================" >> ~/$COIN_NAME.txt
 echo -e " " >> ~/$COIN_NAME.txt
 echo -e "Copy of MASTERNODE file: $CONFIG_FOLDER/masternode.conf" >> ~/$COIN_NAME.txt
 echo -e "================================================================================================================================"  >> ~/$COIN_NAME.txt
 cat "$CONFIG_FOLDER/masternode.conf" >> ~/$COIN_NAME.txt
 echo -e "================================================================================================================================"  >> ~/$COIN_NAME.txt
 echo -e " " >> ~/$COIN_NAME.txt
 echo -e "Copy of CONFIG file: $CONFIG_FOLDER/$CONFIG_FILE" >> ~/$COIN_NAME.txt
 echo -e "================================================================================================================================"  >> ~/$COIN_NAME.txt
 cat "$CONFIG_FOLDER/$CONFIG_FILE" >> ~/$COIN_NAME.txt
 echo -e "================================================================================================================================"  >> ~/$COIN_NAME.txt
 


 # CLEAR TEMP FOLDER
 sudo rm -rf cache
 sudo rm -rf $TMP_FOLDER/* >/dev/null 2>&1
}

install() {
  install_dependences 
	install_swap_file
  backup_configs
	prepare_node
	update_blockchain
	back_configs
	install_service
	last_commits
	if [[ $USE_SENTINEL == Y ]] || [[ $USE_SENTINEL == y ]]; then
	install_sentinel
	fi
	success
}

#main
#default to --without-gui
clear
install --without-gui

